version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "test-application"
        LoadBalancerInfo:
          ContainerName: "test-application"
          ContainerPort: 80
