version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 482315748676.dkr.ecr.us-west-2.amazonaws.com/test-application
      - REPOSITORY_URI=482315748676.dkr.ecr.us-west-2.amazonaws.com/test-application
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test-application .
      - docker tag test-application:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"test-application","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
