apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-application
  template:
    metadata:
      labels:
        app: test-application
    spec:
      containers:
        - name: test-application
          image: 482315748676.dkr.ecr.us-west-2.amazonaws.com/test-application:latest
          ports:
            - containerPort: 80
      nodeSelector:
        eks.amazonaws.com/nodegroup: node_group_2
